title: welcome-to-learn-3
description: welcome-to-learn-3
template:
  repo: welcome-to-learn-3-template
  name: welcome-to-learn-3
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
